location: .gitman
sources:
- name: catkin_simple
  type: git
  repo: https://github.com/catkin/catkin_simple.git
  sparse_paths:
  -
  rev: master
  link: dependencies/catkin_simple
  scripts:
  - git submodule update --init --recursive
- name: nlopt
  type: git
  repo: https://github.com/ctu-mrs/nlopt.git
  sparse_paths:
  -
  rev: master
  link: dependencies/nlopt
  scripts:
  - git submodule update --init --recursive

